# Generated by Django 3.0.6 on 2020-05-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
