# Generated by Django 3.0.6 on 2020-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_auto_20200518_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
