# Generated by Django 3.0.6 on 2020-05-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_auto_20200522_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False, verbose_name='is checked')),
            ],
        ),
    ]
