# Generated by Django 3.0.6 on 2020-05-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_checkform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckForm',
        ),
        migrations.AddField(
            model_name='post',
            name='check',
            field=models.BooleanField(default=False, verbose_name='is checked'),
        ),
    ]
