# Generated by Django 3.0.6 on 2020-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0007_auto_20200525_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='check',
            field=models.BooleanField(default=True),
        ),
    ]
