# Generated by Django 3.0.6 on 2020-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_auto_20200525_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
